[mcp_servers.caveman-shrink]
args = [
    "-y",
    "caveman-shrink",
]
command = "npx"

[mcp_servers.code-review-graph]
args = [
    "-m",
    "code_review_graph",
    "serve",
]
command = "/Library/Frameworks/Python.framework/Versions/3.14/bin/python3.14"
